Dan happy
dan9708/first-repo pull request #1
Opened 2021-07-21 12:55 UTC by dan9708

2021-07-21 13:11 UTC, wuixwui requested changes

2021-07-21 13:11 UTC, wuixwui commented on dana.html
> +	<p></p>
`<p>`시작 태그와 닫는 태그 *사이에* 문장을 작성해주세요! `</p>`

2021-07-21 13:11 UTC, wuixwui commented on dana.html
> +	감사합니다.
줄바꿈을 화면에 표현하실 때는 `<pre>`나 `<br/>`를 사용하시면 좋습니다!

2021-07-21 13:11 UTC, wuixwui commented on dana.html
> + </html>
👍

2021-07-22 04:32 UTC, dan9708 commented on dana.html
> +	감사합니다.
I see

2021-07-22 04:33 UTC, dan9708 commented on dana.html
> +	<p></p>
I added your request.

2021-07-22 04:59 UTC, wuixwui approved these changes

2021-07-22 05:14 UTC, merged